---

nginx:
  image: library/nginx:latest
  ports:
    - "80:80"
  volumes:
    - flice-clients/httpd.conf:/etc/nginx/conf.d/default.conf
    - flice-clients/.tmp/serve:/usr/share/nginx/html
    - flice-clients/bower_components:/usr/share/nginx/html/bower_components

mysql:
  image: lucasgmartins/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD     : ZmxpY2UNCg==
    MYSQL_CORE_DATABASE     : flice-core
    MYSQL_SECURITY_DATABASE : flice-account

account:
  image: lucasgmartins/java8
  ports:
    - "8081:8080"
  links:
    - mysql
  volumes:
    - flice-projects/flice-account/server/target/flice-account.jar:/app/flice-account.jar
  command: java -jar -Dspring.profiles.active=DEV /app/flice-account.jar 