---

core: 
  image: java:8
  ports:
    - "8080:8080"
    - "8000:8000"
  links:
    - mysql
    - account
    - fakes3ssl:flice.s3.amazonaws.com
  working_dir: /app/
  volumes:
    - ./projects/core/server/target/core.jar:/app/core.jar
  command: java -jar
          -Dspring.profiles.active=DEV
          -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n
          -Dmock.s3=http://default:8082
          -Daws.access.token=fakeToken -Daws.secret.key=fakeSecretKey 
          -Dcom.amazonaws.sdk.disableCertChecking=true
          core.jar

account:
  image: java:8
  ports:
    - "8081:8080"
  links:
    - mysql
  working_dir: /app/
  volumes:
    - ./projects/account/server/target/account.jar:/app/account.jar
  command: java -jar 
          -Dspring.profiles.active=DEV 
          account.jar

mysql:
  image: lucasgmartins/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD     : ZmxpY2UNCg==
    MYSQL_CORE_DATABASE     : flice-core
    MYSQL_SECURITY_DATABASE : flice-account

mocks3:
  image : lucasgmartins/mocks3
  ports :
    - "8082:8080"
  links :
    - fakes3ssl:flice.s3.amazonaws.com

fakes3:
  image: smaj/spurious-s3
  hostname: default
  ports:
    - "4569:4569"

fakes3ssl:
  image: cbachich/ssl-proxy
  ports:
    - "443:443"
  links:
    - fakes3:proxyapp
  environment:
    - PORT=443
    - TARGET_PORT=4569